# Generated by Django 6.1.1 on 2026-09-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoWeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('temperature_c', models.FloatField()),
                ('humidity_percent', models.FloatField()),
                ('rainfall_mm', models.FloatField()),
                ('wind_speed_kmh', models.FloatField()),
                ('pressure_hpa', models.FloatField()),
                ('weather_condition', models.CharField(max_length=100)),
            ],
        ),
    ]
